/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacergrafica;

import entidades.Torneio;
import fabricaabstrata.CategoriaAbstrata;
import interfaces.PopularCombo;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import negocio.NTorneio;
import org.joda.time.DateTime;
import util.Validation;

/**
 *
 * @author Rodrigo Leite
 */
public class JanelaTorneioCadastro extends javax.swing.JInternalFrame implements PopularCombo{
    private JDesktopPane principal;

    /**
     * Creates new form frmTipoAssociadoCadoastr
     */
    public JanelaTorneioCadastro() {
        initComponents();
        popularCombo();
    }
    
    public JanelaTorneioCadastro(JDesktopPane principal){
        this();
        this.principal = principal;
    }
    
    public JanelaTorneioCadastro(JDesktopPane principal, Torneio torneio){
        this();
        this.principal = principal;
        preencherTela(torneio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtTaxaInscricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbInicioDia = new javax.swing.JComboBox<>();
        cmbInicioMes = new javax.swing.JComboBox<>();
        cmbInicioAno = new javax.swing.JComboBox<>();
        cmbTerminoDia = new javax.swing.JComboBox<>();
        cmbTerminoMes = new javax.swing.JComboBox<>();
        cmbTerminoAno = new javax.swing.JComboBox<>();
        lblDescricaoAviso = new javax.swing.JLabel();
        lblTaxaAviso = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Cadastro de Torneio");

        jLabel1.setText("Identificador");

        jLabel2.setText("Descrição");

        jLabel3.setText("Taxa de Inscrição");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        txtCodigo.setToolTipText("Código do Tipo Associado");
        txtCodigo.setEnabled(false);

        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyTyped(evt);
            }
        });

        jLabel4.setText("Data Inicio");

        jLabel5.setText("Prazo de Término");

        jLabel6.setText("Categoria");

        lblDescricaoAviso.setPreferredSize(new java.awt.Dimension(41, 41));

        lblTaxaAviso.setPreferredSize(new java.awt.Dimension(41, 20));
        lblTaxaAviso.setRequestFocusEnabled(false);

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTaxaInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTaxaAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbTerminoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbTerminoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbTerminoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbInicioDia, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbInicioMes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbInicioAno, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDescricaoAviso, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(txtDescricao))
                                .addGap(23, 23, 23)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(btnPesquisar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnPesquisar))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescricaoAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbInicioDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbInicioMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbInicioAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbTerminoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTerminoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTerminoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTaxaInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(lblTaxaAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar)
                    .addComponent(btnFechar))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limparTela(){
        txtCodigo.setText("");
        txtDescricao.setText("");
        cmbInicioDia.setSelectedIndex(0);
        cmbInicioMes.setSelectedIndex(0);
        cmbInicioAno.setSelectedIndex(0);
        cmbTerminoDia.setSelectedIndex(0);
        cmbTerminoMes.setSelectedIndex(0);
        cmbTerminoAno.setSelectedIndex(0);
        txtTaxaInscricao.setText("");
        cmbCategoria.setSelectedIndex(0);
        txtDescricao.requestFocus();
        txtCodigo.setEnabled(false);
        btnExcluir.setEnabled(false);
    }
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        try {
            int inicioDia = cmbInicioDia.getSelectedIndex();
            int inicioMes = cmbInicioMes.getSelectedIndex();
            
            int terminoDia = cmbTerminoDia.getSelectedIndex();
            int terminoMes = cmbTerminoMes.getSelectedIndex();
            
            if(inicioMes == 1 || terminoMes == 1){
                if(inicioDia > 28 || terminoDia > 28)
                    throw new Exception("Data inválida!");
            }
            
            ArrayList<String> listS = new ArrayList<>();
            listS.add(txtDescricao.getText());
            listS.add(txtTaxaInscricao.getText());
            Validation.isEmpty(listS);
            
            Torneio torneio = new Torneio(cmbCategoria.getSelectedIndex()+1);
            torneio.setDescricao(txtDescricao.getText());
            torneio.setDataInicio(new java.sql.Date(data()[0].getTime()));
            torneio.setDataTermino(new java.sql.Date(data()[1].getTime()));
            torneio.setTaxa(Double.parseDouble(txtTaxaInscricao.getText().replace(',', '.')));
            
            //se for diferente de nulo e diferente de vazio...
            if(txtCodigo.getText() != null && !txtCodigo.getText().isEmpty()){
                torneio.setId(Integer.parseInt(txtCodigo.getText()));
            }
            new NTorneio().incluir(torneio);
            JOptionPane.showMessageDialog(null, "Operação executada com sucesso");
            limparTela();
                JOptionPane.showMessageDialog(null, "Campos vazios!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        try {
            limparTela();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        try {
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        try {
            if(!txtCodigo.getText().isEmpty()){
                int resposta = JOptionPane.showConfirmDialog(null, "Confirma a "
                        + "exclusão do campeonato?", "Sistema de Controle de Campeonato", 
                        JOptionPane.YES_NO_OPTION);
                if(resposta == JOptionPane.YES_OPTION){
                    new NTorneio().excluir(Integer.parseInt(txtCodigo.getText()));
                    JOptionPane.showMessageDialog(null, "Operação efetuada com sucesso!");

                    limparTela();
                }
            } else{
                JOptionPane.showMessageDialog(null, "Insira o código do campeonato"
                        + " a ser excluído!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        try {
            JanelaPesquisaTorneio janela = new JanelaPesquisaTorneio(principal);
            principal.add(janela);
            janela.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtDescricaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyTyped
        try {
            Validation.limitMaxCaracter(255, txtDescricao.getText(), evt);
        } catch (Exception e) {
            lblDescricaoAviso.setText(e.getMessage());
        }
    }//GEN-LAST:event_txtDescricaoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbInicioAno;
    private javax.swing.JComboBox<String> cmbInicioDia;
    private javax.swing.JComboBox<String> cmbInicioMes;
    private javax.swing.JComboBox<String> cmbTerminoAno;
    private javax.swing.JComboBox<String> cmbTerminoDia;
    private javax.swing.JComboBox<String> cmbTerminoMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblDescricaoAviso;
    private javax.swing.JLabel lblTaxaAviso;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtTaxaInscricao;
    // End of variables declaration//GEN-END:variables

    private Date[] data(){
        try {
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            int inicioDia = cmbInicioDia.getSelectedIndex();
            int inicioMes = cmbInicioMes.getSelectedIndex();
            int inicioAno = cmbInicioAno.getSelectedIndex();

            int terminoDia = cmbTerminoDia.getSelectedIndex();
            int terminoMes = cmbTerminoMes.getSelectedIndex();
            int terminoAno = cmbTerminoAno.getSelectedIndex();
            
            

            String dataInicio = cmbInicioDia.getItemAt(inicioDia) + "/"
                    + cmbInicioMes.getItemAt(inicioMes) + "/"
                    + cmbInicioAno.getItemAt(inicioAno);

            Date daI = df.parse(dataInicio);

            String dataTermino = cmbTerminoDia.getItemAt(terminoDia) + "/" 
                    + cmbTerminoMes.getItemAt(terminoMes) + "/"
                    + cmbTerminoAno.getItemAt(terminoAno);

            Date daT = df.parse(dataTermino);
            
            return new Date[]{daI, daT};
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
            return null;
        }
    }
    
    @Override
    public void popularCombo(){
        try {
            cmbCategoria.removeAllItems();
            ArrayList<String> listaCat = CategoriaAbstrata.getListaDeFabricas();
            
            listaCat.forEach(categoria -> {
                cmbCategoria.addItem(categoria);
            });
            
            for (int i = 1; i <= 31; i++) {
                cmbInicioDia.addItem(i+"");
                cmbTerminoDia.addItem(i+"");
            }
            
            for (int i = 1; i <= 12; i++) {
                cmbInicioMes.addItem(i+"");
                cmbTerminoMes.addItem(i+"");
            }
            
            for (int i = 2018; i <= 2023; i++) {
            cmbInicioAno.addItem(Integer.toString(i));
            cmbTerminoAno.addItem(Integer.toString(i));
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
    
    private void preencherTela(Torneio torneio){
        try {
            DateTime dataIn = new DateTime(torneio.getDataInicio());
            DateTime dataTer = new DateTime(torneio.getDataTermino());
            
            System.out.println(dataIn.getDayOfMonth());
            System.out.println(dataIn.getMonthOfYear());
            System.out.println(dataIn.getYear());
            
            txtCodigo.setText(torneio.getId() + "");
            txtDescricao.setText(torneio.getDescricao());
            cmbCategoria.setSelectedItem(torneio.getCategoria().getDescricao());
            cmbCategoria.setEnabled(false);
            
            cmbInicioDia.setSelectedItem(dataIn.getDayOfMonth()+"");
            cmbInicioMes.setSelectedItem(dataIn.getMonthOfYear()+"");
            cmbInicioAno.setSelectedItem(dataIn.getYear()+"");
            
            cmbTerminoDia.setSelectedItem(dataTer.getDayOfMonth()+"");
            cmbTerminoMes.setSelectedItem(dataTer.getMonthOfYear()+"");
            cmbTerminoAno.setSelectedItem(dataTer.getYear()+"");
            
            txtTaxaInscricao.setText(torneio.getTaxa()+"");
            btnExcluir.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
}
